[project]
name = "taxi-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt-mcp[search]>=0.3.0",
    "dlt[duckdb,workspace]>=1.22.0",
]
